-- Enable plugins
require("plugin_config/lualine")
require("plugin_config/alpha")
require("plugin_config/nvim-autopairs")
require("plugin_config/nvim-tree")
require("plugin_config/treesitter")
require("plugin_config/telescope")
require("plugin_config/completion")
require("plugin_config/lspconfig")
require("plugin_config/neogit")
require("plugin_config/gitsigns")
require("plugin_config/remember")
require("plugin_config/nvim-comment")
require("plugin_config/toggleterm")
